######################################################################
# Automatically generated by qmake (3.0) Mon Mar 12 20:47:54 2018
######################################################################

TEMPLATE = app
TARGET = visu-hex
INCLUDEPATH += .
QT += gui widgets

# Input
SOURCES += main.cpp
